version: "3"
services:
  udagram_reverseproxy:
    image: deeamps/udagram-reverseproxy
  udagram-user-service:
    image: deeamps/udagram-user-service
  udagram-feed-service: 
    image: deeamps/udagram-feed-service
  frontend:
    build:
      context: ../../frontend  
      args:
        - BUILD_ENV=production
    image: deeamps/udagram-frontend
