version: "3"

volumes:
  db-data:
services:
  udagram-reverseproxy:
      image: deeamps/udagram-reverseproxy
      ports:
          - 8000:8000
      restart: always
      depends_on:
        - udagram-user-service
        - udagram-feed-service     
  udagram-user-service:
    image: deeamps/udagram-user-service:latest
    environment:
      POSTGRESS_USERNAME: $POSTGRES_USERNAME
      POSTGRESS_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRESS_DB: $POSTGRES_DB 
      POSTGRESS_HOST: $POSTGRESS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      UDAGRAM_MEDIA_BUCKET: $UDAGRAM_MEDIA_BUCKET
      JWT_SECRET_SECRET: $JWT_SECRET_SECRET
  udagram-feed-service:
    image: deeamps/udagram-feed-service:latest
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $POSTGRES_USERNAME
      POSTGRESS_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRESS_DB: $POSTGRES_DB 
      POSTGRESS_HOST: $POSTGRESS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      UDAGRAM_MEDIA_BUCKET: $UDAGRAM_MEDIA_BUCKET
      JWT_SECRET_SECRET: $JWT_SECRET_SECRET
  frontend:
    image: deeamps/udagram-frontend
    ports:
      - "8100:80"