version: "3"
services:
  udagram-reverseproxy:
      image: deeamps/udagram-reverseproxy:alpha
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - udagram-user-service
        - udagram-feed-service  
  udagram-user-service:
    image: deeamps/udagram-user-service:alpha
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRESS_DB: $POSTGRESS_DB 
      POSTGRESS_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWTSECRET: $JWTSECRET
      URL: "http://localhost:8100"
  udagram-feed-service:
    image: deeamps/udagram-feed-service:alpha
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRESS_DB: $POSTGRESS_DB 
      POSTGRESS_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWTSECRET: $JWTSECRET
      URL: "http://localhost:8100"
  udagram-frontend:
    image: deeamps/udagram-frontend:alpha
    ports:
      - "8100:80"