apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-service
spec:
  selector:
    matchLabels:
      app: udagram-user-service
  template:
    metadata:
      labels:
        app: udagram-user-service
    spec:
      containers:
      - name: udagram-user-service
        image: deeamps/udagram-user-service:latest
        env:
        - name: POSTGRESS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_PASSWORD
        - name: POSTGRESS_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_USERNAME
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: POSTGRESS_DATABASE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_DATABASE
        - name: POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_HOST
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8081
        
