apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-feed-service
  name: udagram-feed-service
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    service: udagram-feed-service

